### PR TITLE
UE 5.3 support

### PR DESCRIPTION
**Pull request by MeetMarkelov**
Fix UE 5.3 compilation error

### CODE REVIEW

**Comment by jorgenpt** [comment]
Looks like it builds with 4.27 and 5.3, so looks good to me. Thanks!
